<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_length" value="1.0"/>
    <xacro:property name="base_width" value="0.6"/>
    <xacro:property name="base_height" value="0.3"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_height" value="0.05"/>

    <xacro:property name="base_mass" value="3.0"/>
    <xacro:property name="wheel_mass" value="1.0"/>


    <xacro:property name="steering_link_radius" value="0.01"/>
    <xacro:property name="steering_link_length" value="0.01"/>
    <xacro:property name="steering_link_mass" value="1"/>

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${(base_height) / 2.0}" rpy="0 0 0"/>
            <material name="olive green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="${base_mass}" l="${base_length}" w="${base_width}" h="${base_height}" xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_height}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_height}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="${wheel_mass}" r="${2*wheel_radius}" h="${2*wheel_height}" xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="rear_right"/>
    <xacro:wheel_link prefix="rear_left"/>
    <xacro:wheel_link prefix="front_left"/>
    <xacro:wheel_link prefix="front_right"/>

    <xacro:macro name="steering_wheel_link" params="prefix">
        <link name="${prefix}_steering_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${steering_link_radius}" length="${steering_link_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${steering_link_radius}" length="${steering_link_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="${steering_link_mass}" r="${2*steering_link_radius}" h="${2*steering_link_length}" xyz="0 0 0" rpy="${pi/2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:steering_wheel_link prefix="front_left"/>
    <xacro:steering_wheel_link prefix="front_right"/>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="base_rear_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_right_wheel_link"/>
        <origin xyz="${(base_length / 2.0) - (wheel_radius)} ${(base_width + wheel_height) / 2.0} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_rear_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_left_wheel_link"/>
        <origin xyz="${(base_length / 2.0) - (wheel_radius)} ${-(base_width + wheel_height) / 2.0} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <!-- <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_right_wheel_link"/>
        <origin xyz="${-((base_length / 2.0) - (wheel_radius))} ${(base_width + wheel_height) / 2.0} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_left_wheel_link"/>
        <origin xyz="${-((base_length / 2.0) - (wheel_radius))} ${-(base_width + wheel_height) / 2.0} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint> -->

    <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="front_right_steering_wheel_link"/>
        <child link="front_right_wheel_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="front_left_steering_wheel_link"/>
        <child link="front_left_wheel_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint> 

    <joint name="base_front_left_steering_wheel_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_left_steering_wheel_link"/>
        <origin xyz="${-((base_length / 2.0) - (wheel_radius))} ${-(base_width + wheel_height) / 2.0} 0" rpy="0 0 0"/>
        <limit effort="100" velocity="100" lower="${-pi / 4.0}" upper="${pi / 4.0}"/>
        <dynamics friction="0.2" damping="0.2"/>
        <axis xyz="0 0 1" />
    </joint> 

    <joint name="base_front_right_steering_wheel_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_right_steering_wheel_link"/>
        <origin xyz="${-((base_length / 2.0) - (wheel_radius))} ${(base_width + wheel_height) / 2.0} 0" rpy="0 0 0"/>
        <limit effort="100" velocity="100" lower="${-pi / 4.0}" upper="${pi / 4.0}"/>
        <dynamics friction="0.2" damping="0.2"/>
        <axis xyz="0 0 1" />
    </joint>
</robot>